openapi: 3.0.0
info:
  title: OAS Diff API
  version: 1.0.0
  x-rosetta:
    id: 5902f8fd-54a3-4b6b-9d62-ddd21ff43fba
paths:
  /tenants:
    post:
      operationId: POST_tenants
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTenantRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                type: object
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a new tenant
  /tenants/{tenant-id}/webhooks:
    get:
      operationId: GET_tenants_{tenant_id}_webhooks
      parameters:
        - in: path
          name: tenant-id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Webhook'
                type: array
          description: OK
        "400":
          description: Bad Request
      summary: Get all webhooks for a tenant
    post:
      operationId: POST_tenants_{tenant_id}_webhooks
      parameters:
        - in: path
          name: tenant-id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWebhookRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                type: object
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a new webhook for a tenant
  /tenants/{tenant-id}/webhooks/{webhook-id}/changelog/{changelog-id}:
    get:
      operationId: GET_tenants_{tenant_id}_webhooks_{webhook_id}_changelog_{changelog_id}
      parameters:
        - in: path
          name: tenant-id
          required: true
          schema:
            type: string
        - in: path
          name: webhook-id
          required: true
          schema:
            type: string
        - in: path
          name: changelog-id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            text/html:
              schema:
                type: string
          description: OK
        "400":
          description: Bad Request
      summary: Get a changelog for a webhook
components:
  schemas:
    CreateTenantRequest:
      properties:
        callback:
          type: string
        email:
          type: string
        slack_channel:
          type: string
        tenant:
          type: string
      type: object
    CreateWebhookRequest:
      properties:
        branch:
          type: string
        owner:
          type: string
        path:
          type: string
        repo:
          type: string
        spec:
          type: string
        webhook_name:
          type: string
      type: object
    Webhook:
      properties:
        branch:
          type: string
        copy:
          type: string
        created:
          type: integer
        id:
          type: string
        name:
          type: string
        owner:
          type: string
        path:
          type: string
        repo:
          type: string
        spec:
          type: string
        tenant_id:
          type: string
        updated:
          type: integer
      type: object

